### ISSUE TITLE
Plugin doesn't work in version 67.2

### ISSUE THREAD

**Issue by petrpavelka** [De-La-Vega/BootstrapGrid#7]
Plugin does nothing after filling the option window. In the previous version of Sketch it worked perfectly.

**Comment by petrpavelka** [comment]
Informations from log file:
```
TypeError: layer.absoluteRect().rulerX is not a function. (In 'layer.absoluteRect().rulerX()', 'layer.absoluteRect().rulerX' is undefined)
    at getLayerParams (/Library/Application Support/com.bohemiancoding.sketch3/Plugins/BootstrapGrid-1.1/Bootstrap grid.sketchplugin/Contents/Sketch/options-window.js:134:57)
```
